/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=.config/wrangler.json --include-runtime=false src/cloudflare-env.d.ts` (hash: 896f1521313859d6c1e2804c9b8c0c2e)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}
